stages:
  train:
    cmd: python src/train.py
    deps:
    - src/train.py
    - data/dataset.csv
    - params.yaml
    outs:
    - model/model.pth
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - src/evaluate.py
    - model/model.pth
    metrics:
    - metrics/accuracy.txt
params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
